services:
  postgres:
    image: postgres:15.17
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB' ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  sigil_cache:
    image: redis:8.6-alpine
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    healthcheck:
      test : ['CMD-SHELL', 'redis-cli -a $$REDIS_PASSWORD ping']
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - sigil_cache:/data

  app:
    build: .
    ports:
      - '8080:8080'
    depends_on:
      postgres:
        condition: service_healthy
      sigil_cache:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_DATA_REDIS_HOST: sigil_cache
      SPRING_DATA_REDIS_PASSWORD: ${REDIS_PASSWORD}


volumes:
  postgres_data:
  sigil_cache:
    driver: local





